name: generate doxygen docs and deploy to github pages

on:
  push:
    branches:
      - "master"
  
  pull_request:
    branches:
      - "master"
jobs:

  gen_docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: build and deploy docs
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: 'Doxygen' 
